SimulationFramework: * Fixed linux build

diff --git a/Simulations/SimulationFramework/DroneControllerSimulator/Makefile b/Simulations/SimulationFramework/DroneControllerSimulator/Makefile
--- a/Simulations/SimulationFramework/DroneControllerSimulator/Makefile
+++ b/Simulations/SimulationFramework/DroneControllerSimulator/Makefile
@@ -1,6 +1,6 @@
 CC = g++
 STD = --std=c++0x
-#WARN = -Wall -Wextra -pedantic
+WARN = -Wall #-Wextra -pedantic
 OPT = -O3
 DEBUG = 
 ifndef REPO_ROOT
@@ -9,20 +9,41 @@ endif
 MADARA_CLIENT = $(REPO_ROOT)/DroneController/packages/madara_client
 INC = -I$(MADARA_ROOT)/include -I$(ACE_ROOT) -I../V-RepImports -I$(MADARA_CLIENT)
 LIB_PATH = -L$(MADARA_ROOT)/lib -L$(ACE_ROOT)/lib
+LIBS = -lMADARA -lACE
 OS = -D__linux
 PLATFORM = -DV_REP
-MADARA_FILES = $(MADARA_CLIENT)/bridge/BridgeAlgorithm.cpp $(MADARA_CLIENT)/bridge/bridge_module.cpp $(MADARA_CLIENT)/area_coverage/SnakeAreaCoverage.cpp $(MADARA_CLIENT)/area_coverage/RandomAreaCoverage.cpp $(MADARA_CLIENT)/area_coverage/InsideOutAreaCoverage.cpp $(MADARA_CLIENT)/area_coverage/AreaCoverage.cpp $(MADARA_CLIENT)/area_coverage/area_coverage_module.cpp $(MADARA_CLIENT)/sensors/sensors_module.cpp $(MADARA_CLIENT)/platforms/v_rep/v-rep_control_functions.cpp $(MADARA_CLIENT)/movement/movement_module.cpp $(MADARA_CLIENT)/utilities/utilities_module.cpp
+MADARA_FILES = $(MADARA_CLIENT)/bridge/BridgeAlgorithm.cpp $(MADARA_CLIENT)/bridge/bridge_module.cpp $(MADARA_CLIENT)/area_coverage/SnakeAreaCoverage.cpp $(MADARA_CLIENT)/area_coverage/RandomAreaCoverage.cpp $(MADARA_CLIENT)/area_coverage/InsideOutAreaCoverage.cpp $(MADARA_CLIENT)/area_coverage/AreaCoverage.cpp $(MADARA_CLIENT)/area_coverage/area_coverage_module.cpp $(MADARA_CLIENT)/sensors/sensors_module.cpp $(MADARA_CLIENT)/platforms/v_rep/v-rep_control_functions.cpp $(MADARA_CLIENT)/movement/movement_module.cpp $(MADARA_CLIENT)/utilities/utilities_module.cpp $(MADARA_CLIENT)/main_functions.cpp
+
+SOURCES = $(MADARA_FILES) Main.cpp
+
+OBJ = $(SOURCES:.cpp=.o)
+
+BOLD  = $(shell tput bold)
+RED   = $(shell tput setaf 1)
+GREEN = $(shell tput setaf 2)
+RESET = $(shell tput sgr0)
+
+OK    = $(BOLD)$(GREEN)[OK]$(RESET)
+FAIL  = $(BOLD)$(RED)[FAIL]$(RESET)
 
 all: DroneControllerSimulator
 
-DroneControllerSimulator: Main.o $(MADARA_FILES)
-	$(CC) $(STD) $(WARN) $(OPT) $(INC) $(LIB_PATH) $(OS) $(PLATFORM) -o DroneControllerSimulator Main.o $(MADARA_FILES) -lACE -lMADARA -ldl -lrt
+DroneControllerSimulator: $(SOURCES) $(OBJ)
+	@echo -n "$(BOLD)Linking $@...$(RESET)"
+	@_ERROR=$$($(CC) $(STD) $(WARN) $(OPT) $(DEBUG) $(INC) $(OS) $(PLATFORM) $(LIB_PATH) $(OBJ) -o $@ $(LIBS) 2>&1); \
+	if [ $$? -eq 0 ]; then echo "$(OK)"; \
+	else echo "$(FAIL)\n$$_ERROR"; exit 1; fi
 
-Main.o: Main.cpp
-	$(CC) $(STD) $(WARN) $(OPT) $(INC) $(OS) -c -o Main.o Main.cpp
+.cpp.o:
+	@echo -n "$(BOLD)Compiling $<...$(RESET)"
+	@_ERROR=$$($(CC) $(STD) $(WARN) $(OPT) $(DEBUG) $(INC) $(OS) $(PLATFORM) -c $< -o $@ 2>&1); \
+	if [ $$? -eq 0 ]; then echo "$(OK)"; \
+	else echo "$(FAIL)\n$$_ERROR"; exit 1; fi
 
 clean:
 	rm -f Main.o
+	make -C $(REPO_ROOT)/DroneController/packages/madara_client clean
 
 realclean: clean
 	rm -f DroneControllerSimulator
+	make -C $(REPO_ROOT)/DroneController/packages/madara_client realclean
diff --git a/Simulations/SimulationFramework/V-RepMadaraQuadrotorControlPlugin/Makefile b/Simulations/SimulationFramework/V-RepMadaraQuadrotorControlPlugin/Makefile
--- a/Simulations/SimulationFramework/V-RepMadaraQuadrotorControlPlugin/Makefile
+++ b/Simulations/SimulationFramework/V-RepMadaraQuadrotorControlPlugin/Makefile
@@ -1,32 +1,42 @@
 CC = g++
 STD = --std=c++0x
-WARN = -Wall -Wextra -pedantic
-#OPT = -O3
-DEBUG = -ggdb
+WARN = -Wall
+OPT = -O3
+#DEBUG = -ggdb
 ifndef REPO_ROOT
   REPO_ROOT=$(HOME)/dev/smash-cmu
 endif
 MADARA_CLIENT = $(REPO_ROOT)/DroneController/packages/madara_client
-INC = -I../V-RepImports -I$(ACE_ROOT) -I$(MADARA_ROOT)/include -I$(MADARA_CLIENT)
+INC = -I../V-RepCommonPluginUtils -I../WindowsMulticastTransport -I../V-RepImports -I$(MADARA_ROOT)/include -I$(MADARA_CLIENT) -I$(ACE_ROOT)
 LIB_PATH = -L$(MADARA_ROOT)/lib -L$(ACE_ROOT)/lib
+LIBS = -lMADARA -lACE
 OS = -D__linux
+
+SOURCES = ../V-RepCommonPluginUtils/LuaExtensionsUtils.cpp ../V-RepCommonPluginUtils/v_repExtLuaExtenderPlugin.cpp ../V-RepImports/v_repLib.cpp LuaCustomFunctions.cpp MadaraQuadrotorControl.cpp
+
+OBJ = $(SOURCES:.cpp=.o)
+
+BOLD  = $(shell tput bold)
+RED   = $(shell tput setaf 1)
+GREEN = $(shell tput setaf 2)
+RESET = $(shell tput sgr0)
+
+OK    = $(BOLD)$(GREEN)[OK]$(RESET)
+FAIL  = $(BOLD)$(RED)[FAIL]$(RESET)
 
 all: libv_repExtMadaraQuadrotorControlPlugin.so
 
-libv_repExtMadaraQuadrotorControlPlugin.so: v_repExtMadaraQuadrotorControlPlugin.o ../V-RepImports/v_repLib.cpp MadaraQuadrotorControl.o LuaCustomFunctions.o v_repLib.o
-	$(CC) $(STD) $(WARN) $(OPT) $(DEBUG) $(OS) $(INC) $(LIB_PATH) -fPIC -shared -o libv_repExtMadaraQuadrotorControlPlugin.so v_repExtMadaraQuadrotorControlPlugin.o v_repLib.o LuaCustomFunctions.o MadaraQuadrotorControl.o -lMADARA -lACE -ldl -lrt
-
-v_repLib.o: ../V-RepImports/v_repLib.cpp
-	$(CC) $(STD) $(WARN) $(OPT) $(DEBUG) $(OS) $(INC) -fPIC -c -o v_repLib.o ../V-RepImports/v_repLib.cpp > /dev/null 2> /dev/null
-
-v_repExtMadaraQuadrotorControlPlugin.o: v_repExtMadaraQuadrotorControlPlugin.cpp v_repExtMadaraQuadrotorControlPlugin.h LuaCustomFunctions.o
-	$(CC) $(STD) $(WARN) $(OPT) $(DEBUG) $(OS) $(INC) -fPIC -c -o v_repExtMadaraQuadrotorControlPlugin.o v_repExtMadaraQuadrotorControlPlugin.cpp
+libv_repExtMadaraQuadrotorControlPlugin.so: $(SOURCES) $(OBJ)
+	@echo -n "$(BOLD)Linking $@...$(RESET)"
+	@_ERROR=$$($(CC) $(STD) -fPIC -shared $(WARN) $(OPT) $(DEBUG) $(INC) $(OS) $(LIB_PATH) $(OBJ) -o $@ $(LIBS) 2>&1); \
+	if [ $$? -eq 0 ]; then echo "$(OK)"; \
+	else echo "$(FAIL)\n$$_ERROR"; exit 1; fi
 	
-MadaraQuadrotorControl.o: MadaraQuadrotorControl.cpp MadaraQuadrotorControl.h
-	$(CC) $(STD) $(WARN) $(OPT) $(DEBUG) $(OS) $(INC) -fPIC -c -o MadaraQuadrotorControl.o MadaraQuadrotorControl.cpp
-
-LuaCustomFunctions.o: LuaCustomFunctions.cpp LuaCustomFunctions.h MadaraQuadrotorControl.h 
-	$(CC) $(STD) $(WARN) $(OPT) $(DEBUG) $(OS) $(INC) -fPIC -c -o LuaCustomFunctions.o LuaCustomFunctions.cpp
+.cpp.o:
+	@echo -n "$(BOLD)Compiling $<...$(RESET)"
+	@_ERROR=$$($(CC) $(STD) -fPIC $(WARN) $(OPT) $(DEBUG) $(INC) $(OS) -c $< -o $@ 2>&1); \
+	if [ $$? -eq 0 ]; then echo "$(OK)"; \
+	else echo "$(FAIL)\n$$_ERROR"; exit 1; fi
 
 clean:
 	rm -f LuaCustomFunctions.o
diff --git a/Simulations/SimulationFramework/V-RepMadaraSystemControllerPlugin/Makefile b/Simulations/SimulationFramework/V-RepMadaraSystemControllerPlugin/Makefile
--- a/Simulations/SimulationFramework/V-RepMadaraSystemControllerPlugin/Makefile
+++ b/Simulations/SimulationFramework/V-RepMadaraSystemControllerPlugin/Makefile
@@ -7,26 +7,42 @@ ifndef REPO_ROOT
   REPO_ROOT = $(HOME)/dev/smash-cmu
 endif
 MADARA_CLIENT = $(REPO_ROOT)/DroneController/packages/madara_client
-INC = -I../V-RepImports -I$(ACE_ROOT) -I$(MADARA_ROOT)/include -I$(MADARA_CLIENT)
+INC = -I../V-RepImports -I$(ACE_ROOT) -I$(MADARA_ROOT)/include -I$(MADARA_CLIENT) -I../V-RepCommonPluginUtils
 LIB_PATH = -L$(MADARA_ROOT)/lib -L$(ACE_ROOT)/lib
+LIBS = -lMADARA -lACE
 OS = -D__linux
+
+SOURCES = v_repExtMadaraSystemController.cpp ../V-RepImports/v_repLib.cpp MadaraSystemController.cpp LuaCustomFunctions.cpp
+SOURCES = ../V-RepCommonPluginUtils/LuaExtensionsUtils.cpp ../V-RepCommonPluginUtils/v_repExtLuaExtenderPlugin.cpp ../V-RepImports/v_repLib.cpp LuaCustomFunctions.cpp MadaraSystemController.cpp
+ 
+OBJ = $(SOURCES:.cpp=.o)
+
+BOLD  = $(shell tput bold)
+RED   = $(shell tput setaf 1)
+GREEN = $(shell tput setaf 2)
+RESET = $(shell tput sgr0)
+
+OK    = $(BOLD)$(GREEN)[OK]$(RESET)
+FAIL  = $(BOLD)$(RED)[FAIL]$(RESET)
 
 all: libv_repExtMadaraSystemControllerPlugin.so
 
-libv_repExtMadaraSystemControllerPlugin.so: v_repExtMadaraSystemController.o ../V-RepImports/v_repLib.cpp MadaraSystemController.o
-	$(CC) $(STD) $(WARN) $(OS) $(INC) $(LIB_PATH) -fPIC -shared -o libv_repExtMadaraSystemControllerPlugin.so v_repExtMadaraSystemController.o ../V-RepImports/v_repLib.cpp LuaCustomFunctions.o MadaraSystemController.o -lMADARA -lACE -ldl -lrt
+libv_repExtMadaraSystemControllerPlugin.so: $(SOURCES) $(OBJ)
+	@echo -n "$(BOLD)Linking $@...$(RESET)"
+	@_ERROR=$$($(CC) $(STD) $(WARN) $(OPT) $(DEBUG) $(INC) $(OS) $(LIB_PATH) $(OBJ) -fPIC -shared -o $@ $(LIBS) 2>&1); \
+	if [ $$? -eq 0 ]; then echo "$(OK)"; \
+	else echo "$(FAIL)\n$$_ERROR"; exit 1; fi
 
-v_repExtMadaraSystemController.o: v_repExtMadaraSystemController.cpp v_repExtMadaraSystemController.h LuaCustomFunctions.o
-	$(CC) $(STD) $(WARN) $(OS) $(INC) -fPIC -c -o v_repExtMadaraSystemController.o v_repExtMadaraSystemController.cpp
-	
-MadaraSystemController.o: MadaraSystemController.cpp
-	$(CC) $(STD) $(WARN) $(OS) $(INC) -fPIC -c -o MadaraSystemController.o MadaraSystemController.cpp
-
-LuaCustomFunctions.o: LuaCustomFunctions.cpp LuaCustomFunctions.h
-	$(CC) $(STD) $(WARN) $(OS) $(INC) -fPIC -c -o LuaCustomFunctions.o LuaCustomFunctions.cpp
+.cpp.o:
+	@echo -n "$(BOLD)Compiling $<...$(RESET)"
+	@_ERROR=$$($(CC) $(STD) $(WARN) $(OPT) $(DEBUG) $(INC) $(OS) -fPIC -c $< -o $@ 2>&1); \
+	if [ $$? -eq 0 ]; then echo "$(OK)"; \
+	else echo "$(FAIL)\n$$_ERROR"; exit 1; fi
 
 clean:
 	rm -f *.o
+	make -C ../V-RepImports clean
+	make -C ../V-RepCommonPluginUtils clean
 
 realclean: clean
 	rm -f *.so
